app/views.py
from flask import render_template, flash, redirect, url_for, Blueprint, request
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from datetime import datetime, date
from forms import UserForm, LoginForm, UserUpdateForm, FoodForm
from models import Users, Foods, db
# from openai import OpenAI

# client = OpenAI(
#   api_key='sk-proj-bOn2aUe1oCoXwxtsVDePT3BlbkFJQN2LRI8Aj9hkBTepVwnq',
# )

views = Blueprint('views', __name__)

@views.route('/')
def index():
    return render_template('index.html')

@views.route('/register', methods=['GET', 'POST'])
def register():
    form = UserForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        user_username = Users.query.filter_by(
            username=form.username.data).first()
        if user is None and user_username is None:
            hashed_pass = generate_password_hash(
                form.password_hash.data, "pbkdf2:sha256")
            user = Users(username=form.username.data,
                         email=form.email.data, password_hash=hashed_pass)
            db.session.add(user)
            db.session.commit()
            flash("User created", "alert alert-success alert-dismissible fade show")
            form.username.data = ''
            form.email.data = ''
            form.password_hash.data = ''
            return redirect(url_for('views.login'))
        elif user and user_username:
            flash("Username and email are taken",
                  "alert alert-danger alert-dismissible fade show")
            form.username.data = ''
            form.email.data = ''
        elif user and not user_username:
            flash("Email is taken",
                  "alert alert-danger alert-dismissible fade show")
            form.email.data = ''
        elif user_username and not user:
            flash("Username is taken",
                  "alert alert-danger alert-dismissible fade show")
            form.username.data = ''
    all_users = Users.query.order_by(Users.date_added)
    return render_template('register.html', form=form, all_users=all_users)


@views.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password_hash, form.password.data):
                login_user(user)
                flash("You are logged in",
                      "alert alert-success alert-dismissible fade show")
                return redirect(url_for('views.profile'))
            else:
                flash("Wrong password - try again",
                      "alert alert-danger alert-dismissible fade show")
        elif user is None:
            user = Users.query.filter_by(email=form.username.data).first()
            if user:
                if check_password_hash(user.password_hash, form.password.data):
                    login_user(user)
                    flash("You are logged in",
                          "alert alert-success alert-dismissible fade show")
                    return redirect(url_for('views.profile'))
                else:
                    flash("Wrong password - try again",
                          "alert alert-danger alert-dismissible fade show")
        else:
            flash("User does not exist",
                  "alert alert-danger alert-dismissible fade show")
    return render_template('login.html', form=form)

@views.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = UserUpdateForm()
    if form.validate_on_submit():
        if Users.query.filter_by(username=form.username.data).first() and form.username.data != current_user.username:
            flash('Username is taken',
                  "alert alert-danger alert-dismissible fade show")
            current_user.email = form.email.data
        elif Users.query.filter_by(email=form.email.data).first() and form.email.data != current_user.email:
            flash('Email address is taken',
                  "alert alert-danger alert-dismissible fade show")
            current_user.username = form.username.data
        else:
            current_user.email = form.email.data
            current_user.username = form.username.data
            db.session.commit()
            flash("User updated",
                  "alert alert-success alert-dismissible fade show")
    return render_template('user_settings.html', form=form)


@views.route('/user/delete/<int:id>')
@login_required
def delete_user(id):
    user_to_delete = Users.query.get_or_404(id)
    if current_user.id == user_to_delete.id:
        try:
            db.session.delete(user_to_delete)
            db.session.commit()
            flash("User deleted",
                  "alert alert-success alert-dismissible fade show")
        except:
            flash("Something went wrong... try again later",
                  "alert alert-danger alert-dismissible fade show")
    return redirect(url_for('views.register'))

@views.route('/profile')
@login_required
def profile():
    foods = Foods.query.order_by(Foods.expiry_date)
    mails = []
    current = date.today()
    for food in foods:
        expiry = food.expiry_date.date()
        delta = expiry - current
        if current_user.id == food.user.id and delta.days >= 1 and delta.days <= 3:
            mails.append(food)
    return render_template('profile.html', mails=mails, date_current=current)

@views.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash("You have been logged out",
          "alert alert-success alert-dismissible fade show")
    return redirect(url_for('views.login'))

@views.route('/add-food', methods=['GET', 'POST'])
@login_required
def add_food():
    form = FoodForm()
    if form.validate_on_submit():
        user = current_user.id
        food = Foods(user_id=user, name=form.name.data, expiry_date=form.date.data)
        db.session.add(food)
        db.session.commit()
        flash(f"{food.name} added",
              "alert alert-success alert-dismissible fade show")
        form.name.data = ''
        form.date.data = ''
        return redirect(url_for('views.foods'))
    return render_template('add_food.html', form=form)

@views.route('/foods/<int:id>')
@login_required
def food(id):
    food = Foods.query.get_or_404(id)
    if current_user.id == food.user.id:
        return render_template('food.html', food=food)
    else:
        flash("Food does not exist",
              "alert alert-danger alert-dismissible fade show")
        return redirect(url_for('views.foods'))


@views.route('/food/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def food_settings(id):
    food = Foods.query.get_or_404(id)
    if current_user.id == food.user.id:
        form = FoodForm()
        if form.validate_on_submit():
            food.name = form.name.data
            food.expiry_date = form.date.data
            db.session.commit()
            flash("Food updated",
                  "alert alert-success alert-dismissible fade show")
            return redirect(url_for('views.foods'))
        form.name.data = food.name
        form.date.data = food.expiry_date
        return render_template('food_settings.html', form=form)
    else:
        flash("Food does not exist",
              "alert alert-danger alert-dismissible fade show")
        return redirect(url_for('views.foods'))


@views.route('/foods/delete/<int:id>')
@login_required
def delete_food(id):
    food_to_delete = Foods.query.get_or_404(id)
    if current_user.id == food_to_delete.user.id:
        try:
            db.session.delete(food_to_delete)
            db.session.commit()
            flash("Food deleted",
                  "alert alert-success alert-dismissible fade show")
            return redirect(url_for('views.foods'))
        except:
            flash("Something went wrong... try again later",
                  "alert alert-danger alert-dismissible fade show")
            return redirect(url_for('views.foods'))
    else:
        flash("This course does not exist",
              "alert alert-danger alert-dismissible fade show")
        return redirect(url_for('views.foods'))


@views.route('/foods')
@login_required
def foods():
    foods = Foods.query.order_by(Foods.expiry_date)
    createdfoods = []
    for food in foods:
        if current_user.id == food.user.id:
            createdfoods.append(food)
    current = date.today()
    return render_template('foods.html', foods=createdfoods, date_current=current)


@views.route('/suggestions')
@login_required
def suggestions():
    return render_template('suggestions.html')

@views.route('/feedback', methods=['GET', 'POST'])
@login_required
def feedback():
    if request.method == "POST":
        return redirect(url_for("views.profile"))
    return render_template('feedback.html')

@views.route("/coupons")
@login_required
def coupons():
    return render_template("coupons.html")

@views.route("/coupon/<int:id>")
@login_required
def coupon(id):
    coupons = ["Food Basics", "Costco", "Freshco", "Walmart"]
    return render_template("coupon.html", name=coupons[id-1])

@views.route("/recipes")
@login_required
def recipes():
    return render_template("recipes.html")

app/templates/add_food.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add food</title>
</head>
<body>
    {% extends 'base.html' %}
    {% set active = 'add_food' %}
    {% block content %}
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="{{ category }}">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </div>
      {% endfor %}
      <br>
      <div class="card mx-auto" style="width: 40rem;">
        <div class="card-body p-5">
          <h2 class="mb-5">Add food item</h2>
          <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control", placeholder="Name") }}
            <br>
            {{ form.date.label(class="form-label") }}
            {{ form.date(class="form-control") }}
            <br>
            <div class="d-grid">
              {{ form.submit(class="btn btn-primary") }}
            </div>
          </form>
        </div>
      </div>
      <br>
    {% endblock %}
</body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<title></title>
</head>

<body>
    {% include 'navbar.html' %}
    <br>
    <br>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

app/templates/coupon.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet", type ="text/css", href="../static/landing_page.css">
  <title>Coupon</title>

</head>

<body class="background pb-5 bg-dark">
  {% extends 'base.html' %}
  {% set active = 'coupons' %}
  {% block content %}
  <h1 class="banner blurAnimation", style="padding: 15px;">Coupons for {{ name }}</h1>
  <br><br><br>
  {% if name == "Food Basics" %}
    <img height="650" width="350" src="../static/food_basics_flyers.jpg" alt="food basics">
  {% elif name == "Costco" %}
    <img height="650" width="350" src="../static/costco_coupons.jpg" alt="costco">
  {% elif name == "Freshco" %}
    <img height="350" width="650" src="../static/freshco_coupon.jpg" alt="freshco">
  {% else %}
    <img height="350" width="650" src="../static/walmart_coupon.jpg" alt="walmart">
  {% endif %}
  {% endblock %}
</body>

</html>

app/templates/coupons.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet", type ="text/css", href="../static/landing_page.css">
  <title>Recipes</title>

</head>

<body class="background pb-5 bg-dark">
  {% extends 'base.html' %}
  {% set active = 'coupons' %}
  {% block content %}
  <h1 class="banner blurAnimation", style="padding: 15px">Coupons from our Partners</h1>
  <br><br><br>
  <div class="row row-cols-1 row-cols-md-4 g-4">
    <div class="col">
      <div class="card h-100">
        <img src="static/food_basics.png" alt="food basics" class="card-img-top pt-3">
        <div class="card-body">
        </div>
        <div class="card-footer bg-transparent">
          <a href="{{ url_for('views.coupon', id=1) }}" class="btn btn-outline-primary btn-sm">See Coupon</a>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <img src="static/costco.png" alt="Costco" class="card-img-top pt-3">
        <div class="card-body">
        </div>
        <div class="card-footer bg-transparent">
          <a href="{{ url_for('views.coupon', id=2) }}" class="btn btn-outline-primary btn-sm">See Coupon</a>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <img src="static/freshco.png" alt="Freshco" class="card-img-top pt-3">
        <div class="card-body">
        </div>
        <div class="card-footer bg-transparent">
          <a href="{{ url_for('views.coupon', id=3) }}" class="btn btn-outline-primary btn-sm">See Coupon</a>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <img src="static/walmart.jpg" alt="Walmart" class="card-img-top pt-3">
        <div class="card-body">
        </div>
        <div class="card-footer bg-transparent">
          <a href="{{ url_for('views.coupon', id=4) }}" class="btn btn-outline-primary btn-sm">See Coupon</a>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</body>

</html>

app/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet", type ="text/css", href="../static/landing_page.css">
    <title>Login</title>
</head>
<body class="background2 bg-dark">
    {% extends 'base.html' %}
    {% set active = 'feedback' %}
    {% block content %}
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="{{ category }}">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </div>
      {% endfor %}
      <br>
      <div class="card mx-auto" style="width: 26rem;">
        <div class="card-body p-4">
          <h3 class="mb-4">Enter feedback</h3>
          <form method="POST">
            <textarea class="form-control" placeholder="Your feedback" rows="10"></textarea>
            <br>
            <input type="Submit" class="btn btn-primary" value="Submit">
          </form>
        </div>
      </div>
      <br>
    {% endblock %}
</body>
</html>

app/templates/food.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet", type ="text/css", href="../static/landing_page.css">
    <title></title>
  </head>
  <body class="background bg-dark">
    {% extends 'base.html' %}
    {% block content %}
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="{{ category }}">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </div>
      {% endfor %}
      <div class="shadow p-3 mb-5 bg-body rounded">
        {{ food.name }}
        <br>
        {{ food.date }}
        <br>
      </div>
      <br>
    </body>
  {% endblock %}
</html>

app/templates/food_settings.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Food settings</title>
  </head>
  <body>
    {% extends 'base.html' %}
    {% block content %}
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="{{ category }}">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </div>
      {% endfor %}
      <div class="card mx-auto" style="width: 40rem;">
        <div class="card-body p-5">
          <h2 class="mb-5">Edit this food</h2>
          <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control", placeholder="Name") }}
            <br>
            {{ form.date.label(class="form-label") }}
            {{ form.date(class="form-control") }}
            <br>
            <div class="d-grid">
              {{ form.submit(class="btn btn-primary") }}
            </div>
          </form>
        </div>
      </div>
    {% endblock %}
  </body>
</html>

app/templates/foods.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet", type ="text/css", href="../static/landing_page.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foods</title>
  </head>
  <body class="background bg-dark">
    {% extends 'base.html' %}
    {% set active = 'foods' %}
    {% block content %}
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="{{ category }}">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </div>
      {% endfor %}
      <br>
      {% if foods %}
        <div class="row row-cols-1 row-cols-md-4 g-4">
          {% for food in foods %}
            <div class="col">
              {% if (food.expiry_date.date() - date_current).days >= 1 and (food.expiry_date.date() - date_current).days <= 3 %}
              <div class="card h-100 border border-warning border-5">
                <div class="card-body">
                  <h4><a href="{{ url_for('views.food', id=food.id) }}">{{ food.name }}</a></h4>
                  <small>{{ food.expiry_date.date() }}</small>
                  <br>
                </div>
                <div class="card-footer bg-transparent">
                  <a href="{{ url_for('views.food_settings', id=food.id) }}" class="btn btn-outline-primary btn-sm">Edit Info</a>
                  <a href="{{ url_for('views.delete_food', id=food.id) }}" class="btn btn-outline-danger btn-sm">Delete</a>
                </div>
              </div>
              {% elif (food.expiry_date.date() - date_current).days < 1 %}
              <div class="card h-100 border border-danger border-5">
                <div class="card-body">
                  <h4><a href="{{ url_for('views.food', id=food.id) }}">{{ food.name }}</a></h4>
                  <small>{{ food.expiry_date.date() }}</small>
                  <br>
                </div>
                <div class="card-footer bg-transparent">
                  <a href="{{ url_for('views.food_settings', id=food.id) }}" class="btn btn-outline-primary btn-sm">Edit Info</a>
                  <a href="{{ url_for('views.delete_food', id=food.id) }}" class="btn btn-outline-danger btn-sm">Delete</a>
                </div>
              </div>
              {% else %}
              <div class="card h-100">
                <div class="card-body">
                  <h4><a href="{{ url_for('views.food', id=food.id) }}">{{ food.name }}</a></h4>
                  <small>{{ food.expiry_date.date() }}</small>
                  <br>
                </div>
                <div class="card-footer bg-transparent">
                  <a href="{{ url_for('views.food_settings', id=food.id) }}" class="btn btn-outline-primary btn-sm">Edit Info</a>
                  <a href="{{ url_for('views.delete_food', id=food.id) }}" class="btn btn-outline-danger btn-sm">Delete</a>
                </div>
              </div>
              {% endif %}
            </div>
          {% endfor %}
        </div>
      {% else %}
        <h2>You have no foods added. Press the button in the top right corner to create one.</h2>
      {% endif %}
    {% endblock %}
  </body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" , type="text/css" , href="../static/landing_page.css">
    <!-- Access google fonts api to obtain the fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!--Fonts Used-->
    <link href="https://fonts.googleapis.com/css2?family=Briem+Hand:wght@100..900&display=swap" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Briem+Hand:wght@100..900&family=Teachers:ital,wght@0,400..800;1,400..800&display=swap"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <title>Title</title>
    <!-- <link rel="icon" type="image/x-icon" href=""> --> <!--URL for Facivon Image-->
    <script>
        onmousemove = function (e) {
            // console.log("mouse location:", e.clientX, e.clientY);
            document.getElementById("mouse").style.top = (e.clientY - 25) + "px"
            document.getElementById("mouse").style.left = (e.clientX - 25) + "px"
        }
    </script>
</head>

<body class="background white-text bg-dark pb-5">
    {% extends 'base.html' %}
    {% set active = 'index' %}
    {% block content %}
    <div class="mouse-tracker" , id="mouse"></div>
    <div class="text-center banner handwriting opacityAnimation">
        <h1>Welcome to EcoEats!</h1h1>
    </div>
    <p class="introduction">Tired of seeing perfectly good food being thrown out? Wanting to manage your budget and <br>
        have your own
        personal AI constantly creating analytics and aiding you? You've came to the right place! <br><br>

        EcoEats is an all in one application used for tracking, reducing, analyzing, and preventing food waste <br>
        in your daily life. With the app, you can easily log in your foods, track consumption, and discover creative
        <br>
        ways of reducing food waste!
    </p>
    <hr><br><br>
    <!--
        <img id ="logo" href="../static/Favicon.png">
    -->
    <div class="backing blurAnimation">
        <h2 class="font" , style="text-align: center;"> Why use EcoEats? </h2>
        <ul class="line-break" style="margin-left: 45px;">
            <li>
                <strong>Reduce Waste:</strong> Say goodbye to wasting large amounts of food. EcoEats will make the most
                of every single ingredient in your home!
            </li>
            <li>
                <strong>Save Money</strong> By optimizing and analyzing food consumption and shopping habits, you'll be
                saving money consistently and minimizing unnecessary purchases!
            </li>
            <li>
                <strong>Save the Planet</strong> Every meal is important. When you reduce your food waste, you are
                contributing
                to ensuring the health of your planet.
            </li>
        </ul>
    </div>
    <br><br><br>
    <div class="teachers">
        <h2>How does it work? </h2>
        <hr>
        <ol>
            <li>
                <strong>Log Your Food:</strong> Easily input current foods and ingredients in your home and we'll do the
                rest!
            </li>

            <li>
                <strong>Track Consumption:</strong> Monitor food usage and waste with simple diagrams and graphs.
            </li>

            <li>
                <strong>Get Personalized Reccomendations:</strong> recieve suggestions from a specialized AI that uses
                machine learning
                and is specified to your preferences to get meal ideas, recipes, and more based off your ingredients.
            </li>

            <li>
                <strong>Give Us Feedback: </strong> Send us feedback on our page and we'll use it to improve the
                effectiveness
                of the application
            </li>

            <li>
                <strong>Recieve Rewards:</strong> Recieve special coupons for popular food industries as rewards for
                reducing your
                food waste!
            </li>
    </div>

    <!--
    <br><br><br><br><br><br><br><br><br>
    <h2 class="bottom">Together, let's waste less and eat better!<h2>
    -->
    <br>
    <hr>
    <br>
    <h2>How much waste?</h2>
    <div id="myPlot" style="width:100%;max-width:700px"></div>

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script>
        const xArray = ["On farm", "Restaurants and hotels", "Processing", "Retail", "Transport and distribution", "Consumers"];
        const yArray = [10, 9, 20, 10, 4, 47];

        const layout = { title: "Food Waste in Value Food Chain" };

        const data = [{ labels: xArray, values: yArray, type: "pie" }];

        Plotly.newPlot("myPlot", data, layout);
    </script>
    {% endblock %}
</body>

</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet", type ="text/css", href="../static/landing_page.css">
    <title>Login</title>
</head>
<body class="background">
    {% extends 'base.html' %}
    {% set active = 'login' %}
    {% block content %}
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="{{ category }}">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </div>
      {% endfor %}
      <br>
      <div class="card mx-auto" style="width: 20rem;">
        <div class="card-body p-4">
          <h3 class="mb-4">Sign in</h3>
          <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.username.label(class="form-label") }}
            {{ form.username(class="form-control", placeholder="Username") }}
            <br>
            {{ form.password.label(class="form-label") }}
            {{ form.password(class="form-control", placeholder="Password") }}
            <br>
            <div class="d-grid">
              {{ form.signin(class="btn btn-primary") }}
            </div>
          </form>
        </div>
      </div>
      <br>
    {% endblock %}
</body>
</html>

app/templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" , type="text/css" , href="../static/landing_page.css">
  <title>Profile</title>
  </script>
</head>

<body class="background white-text bg-dark">
  {% extends 'base.html' %}
  {% set active = 'profile' %}
  {% block content %}
  {% for category, message in get_flashed_messages(with_categories=true) %}
  <div class="{{ category }}">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </div>
  {% endfor %}
  <h1 class="blurAnimation blur">Welcome, {{ current_user.username|title }}!</h1>
  <br>
  <br>
  <h3>Notifications</h3>
  {% if mails %}
  <div class="blur">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Sender</th>
          <th scope="col">Food</th>
          <th scope="col">Message</th>
        </tr>
      </thead>
      <tbody>
        {% for mail in mails %}
        <tr>
          <td> EcoEats </td>
          <td> {{ mail.name }} </td>
          {% if (mail.expiry_date.date() - date_current).days == 1 %}
          <td class="text-warning"> Expires in 1 day </td>
          {% elif (mail.expiry_date.date() - date_current).days > 1 %}
          <td> Expires in {{ (mail.expiry_date.date() - date_current).days }} days </td>
          {% else %}
          <td class="text-danger"> Expired </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <div class="white-text">You have no current notifications.</div>
  {% endif %}
  {% endblock %}

</html>

app/templates/recipes.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" , type="text/css" , href="../static/landing_page.css">
    <title>Coupons</title>

</head>

<body class="background pb-5 bg-dark">
    {% extends 'base.html' %}
    {% set active = 'recipes' %}
    {% block content %}
    {% for category, message in get_flashed_messages(with_categories=true) %}
    <div class="{{ category }}">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </div>
    {% endfor %}
    <br>
    <div class="card mx-auto" style="width: 26rem;">
        <div class="card-body p-4">
            <h3 class="mb-4">Recipes</h3>
            <p>
                Here are some AI generated recipe ideas based on the ingredients you have:
            </p>
            <p>Caesar salad</p>
            <p>Spinach lasagna</p>
            <p>Guacamole</p>
            <button class="btn btn-primary">Generate new recipes</button>
        </div>
    </div>
    {% endblock %}
</body>

</html>

app/templates/user_settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" , type="text/css" , href="../static/landing_page.css">
    <title>User Settings</title>
</head>
<body class="background">
    {% extends 'base.html' %}
    {% block content %}
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="{{ category }}">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </div>
      {% endfor %}
      <br>
      <div class="card mx-auto" style="width: 26rem;">
        <div class="card-body p-4">
          <h3 class="mb-4">User info</h3>
          <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.username.label(class="form-label") }}
            {{ form.username(class="form-control", value=current_user.username, placeholder="Username") }}
            <br>
            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control", value=current_user.email, placeholder="Email") }}
            <br>
            <div class="d-grid gap-2">
              {{ form.update(class="btn btn-outline-primary") }}
              <a href="{{ url_for('views.delete_user', id=current_user.id) }}" class="btn btn-outline-danger">Delete</a>
            </div>
          </form>
        </div>
      </div>
    {% endblock %}
</body>
</html>